### ISSUE TITLE
can not download

### ISSUE THREAD

**Issue by JOY0430STAR** [hanyangclarence/UniMuMo#1]
The weight of UniMuMo consists of three parts: a music VQ-VAE, a motion VQ-VAE and a music-motion LM. For inference, please download the unified weight that includes all three parts from [here](https://github.com/hanyangclarence/UniMuMo/blob/main). For data preprocessing or training, only one or two parts of them are required for each stage. So please download the separate weights from [here](https://github.com/hanyangclarence/UniMuMo/blob/main).

**Comment by hanyangclarence** [comment]
We will release the weight soon!
